### ISSUE TITLE
MySql generates incorrect yaml for ConfigMap

### ISSUE THREAD

**Issue by ScottGuymer** [ksonnet/mixins#67]
I ran into a problem when trying to sue the MySql template

When it generates the `ConfigMap` it seems to add in a key under the data property called `configurationFiles:`

You can see the line here int he generated example
https://github.com/ksonnet/parts/blob/master/incubator/mysql/examples/generated.yaml#L4

When you try to apply this example to a cluster 

```
apiVersion: v1
data: 
  configurationFiles: 
    mysql.cnf: |
        - [mysqld]
        skip-name-resolve
kind: ConfigMap
metadata: 
  name: mysql
  namespace: default
```

you get the following response

```
error: error validating "test.yaml": error validating data: ValidationError(ConfigMap.data.configurationFiles): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false
```

But when you  remove the line containing `configurationFiles:` it applies sucessfully
